version: '3.8'

services:
  api:
    build: .
    image: docker_system_tracking_api:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: action
    networks:
      - postgres_network
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: docker-system-tracking
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge